/*
 * Copyright © 2018 Martins Anerua
 */

package anerua.mcode;

import javax.swing.JTextArea;

public class Help {
	
	public void HelpG(JTextArea view) {
		view.append("\n"
				+ "=============================================================="
				+ "\n"
				+ "	ACAD			- Lists all course material"
				+ "\n"
                                + "	ARDUINO			- Arduino"
				+ "\n"
				+ "	BLUE			- Send or receive file through bluetooth"
				+ "\n"
                                + "	BLUESTACKS		- Bluestacks"
				+ "\n"
				+ "	CALC			- Calculator"
				+ "\n"
                                + "	CAVAJ			- Cavaj Java Decompiler"
				+ "\n"
				+ "	CIR			- Proteus"
				+ "\n"
				+ "	CMD			- Command Prompt"
				+ "\n"
                                + "	COMP			- Computer stuffs pdf"
				+ "\n"
				+ "	CPLUS 			- CodeBlocks"
				+ "\n"
				+ "	CLS 			- Clear command window"
				+ "\n"
				+ "	DATE 			- Displays current time and date"
				+ "\n"
				+ "	DOWN 			- Downloads folder"
				+ "\n"
                                + "	ELECTRIC		- Electric App"
				+ "\n"
				+ "	EXIT			- Exit the current mCode window"
				+ "\n"
				+ "	FILE			- Windows explorer"
				+ "\n"
//				+ "	FILM			- VLC"
//				+ "\n"
				+ "	FOXIT			- Foxit Reader"
				+ "\n"
				+ "	FTP			- FTP"
				+ "\n"
//				+ "	GAME			- no args : Games explorer\n"
//				+ "				  '-c'    : Chess\n"
//				+ "				  '-f'    : Free Cell\n"
//				+ "				  '-h'    : Hearts\n"
//				+ "				  '-m'    : Mahjong\n"
//				+ "				  '-ms'   : Minesweeper\n"
//				+ "				  '-p'    : Purble Place\n"
//				+ "				  '-s'    : Solitaire\n"
//				+ "				  '-ss'   : Spider Solitaire"
//				+ "\n"
				+ "	HELP			- This list of commands"
				+ "\n"
				+ "	HIBERNATE		- Hibernate the computer"
				+ "\n"
				+ "	HIDE			- Minimize command window"
				+ "\n"
                                + "	HTML			- HTML-Kit App"
				+ "\n"
				+ "	JAVA			- no args : NetBeans\n"
				+ "				  '-e'    : Eclipse\n"
				+ "				  '-n'    : NetBeans"
				+ "\n"
				+ "	KEY			- On-Screen keyboard"
				+ "\n"
				+ "	MAP			- Character map"
				+ "\n"
//				+ "	MEE			- no args : MEE206 folder\n"
//				+ "				  '-b'    : Beer and Johnston\n"
//				+ "				  '-bs'   : Beer and Johnston solution manual"
//				+ "\n"
//				+ "	MTH			- K A Stroud"
//				+ "\n"
				+ "	MUSIC			- Windows media player"
				+ "\n"
				+ "	NET			- no args : Mozilla Firefox\n"
				+ "				  '-c'    : Google Chrome\n"
				+ "				  '-f'    : Mozilla Firefox\n"
				+ "				  '-i'    : Internet Explorer\n"
				+ "				  '-o'    : Opera Browser\n"
				+ "				  '-u'    : UCBrowser"
				+ "\n"
				+ "	NOTE			- Notepad"
				+ "\n"
				+ "	NTWRK			- Networking for Dummies"
				+ "\n"
				+ "	OFF 			- no args : Microsoft Office folder\n"
				+ "				  '-a'    : MS Access\n"
				+ "				  '-e'    : Excel\n"
				+ "				  '-i'    : InfoPath\n"
				+ "				  '-o'    : Outlook\n"
				+ "				  '-p'    : Publisher\n"
				+ "				  '-pp'   : Power Point\n"
				+ "				  '-w'    : MS Word"
				+ "\n"
				+ "	PAINT			- MS Paint"
				+ "\n"
                                + "	PHOTOSHOP		- Photoshop CS6"
				+ "\n"
				+ "	PICS			- Pictures"
				+ "\n"
				+ "	PYTHON			- Python"
				+ "\n"
                                + "	RAR			- WinRAR"
				+ "\n"
				+ "	RECORD			- Recorder"
				+ "\n"
				+ "	RESTART			- Restart the computer"
				+ "\n"
				+ "	SETTINGS		- Control panel"
				+ "\n"
				+ "	SHUTDOWN		- Shutdown the computer"
				+ "\n"
				+ "	SNIP			- Snipping tool"
				+ "\n"
				+ "	STICKY			- Sticky note"
				+ "\n"
				+ "	TASK			- Task manager"
				+ "\n"
				+ "	TIME 			- Displays current time and date"
				+ "\n"
				+ "	TYPE			- Mavis Beacon"
				+ "\n"
                                + "	CONFIG			- Configure shell properties"
				+ "\n"
				+ "==============================================================");
	}
}
